### PR TITLE
Update Veracode plugin to latest supported plugin.

### PR DESCRIPTION
**Pull request by arknoll**

### CODE REVIEW

**Comment by Evildethow** [comment]
@reviewbybees

**Comment by oleg-nenashev** [comment]
This change is not reviewable due to massive formatting changes and missing descriptions of intended changes. Please update the PR summary and describe what happens in this pull request.

Minor comments:
* .DS_Store should not be included into the repository
* The changes seem to be incompatible with previous version (both binary API and persisted data). So people updating this plugin must be warned about it (is it really required)
* Storage of binary files in the repo is acceptable sometimes, but generally it's a bad practice (especially from the legislation side). I don't see usages of these files. What is the purpose?

**Comment by arknoll** [comment]
Hi @oleg-nenashev,

I received this code from Veracode. According to them this is the only supported plugin to connect to their system. The existing plugin in this repo no longer works. I am not a java developer, this was just a cut and paste job.

**Comment by oleg-nenashev** [comment]
@arknoll OK, let's see what @mbockus says.
I don't know Veracode internals, but maybe the current plugin version is still being used (e.g. for old on-premise instances).

**Comment by arknoll** [comment]
@oleg-nenashev I've heard nothing from @mbockus. Is there anything you can do to push this along, at least in this repo?

**Comment by mbockus** [comment]
@oleg-nenashev @arknoll Sorry for not chiming in. I initially created the plugin because a Veracode jenkins plugin did not exist. We needed a plugin that would only submit scans on a specified frequency. I haven't confirmed that the existing Veracode plugin meets that need. If it did, then I would love to integrate the supported veracode plugin. 

Are we aware of a contact at veracode that would support the decision to open source their plugin. Since it hasn't previously been contributed to the jenkins plugin repository, I thought they might have a reason for that.

**Comment by arknoll** [comment]
Hi @mbockus, we are currently determining a veracode contact.

**Pull request closed without merging**
